import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const ttHovesPro = localFont({
  src: [
    {
      path: "../../public/fonts/TT-Hoves-Pro/TT-Hoves-Pro-normal-400-100.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/TT-Hoves-Pro/TT-Hoves-Pro-normal-500-100.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/TT-Hoves-Pro/TT-Hoves-Pro-normal-600-100.ttf",
      weight: "600",
      style: "normal",
    },
  ],
  variable: "--font-tt-hoves-pro",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ttHovesPro.variable} font-sans antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
